---
# Available parameters and their default values for the Consul chart.
# Server, when enabled, configures a server cluster to run. This should
# be disabled if you plan on connecting to a Consul cluster external to
# the Kube cluster.
global:
  # image: hashicorpdev/consul
  # imageK8S: hashicorpdev/consul-k8s:crd-controller-base-latest
  name: consul
server:
  replicas: 1
  bootstrapExpect: 1

  extraConfig: |
    {
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-kube-prometheus-prometheus.default.svc:9090"
        }
      }
    }

controller:
  enabled: true
ui:
  enabled: true
connectInject:
  enabled: true
  default: false  # true will inject by default, otherwise requires annotation

  # Requires Consul v1.5+ and consul-k8s v0.8.1+
  centralConfig:
    enabled: "true"